name: 'Save precondition indexes from GitHub repositry for generate code'
description: 'コード生成のための前提条件として GitHub リポジトリの情報を Cloud Storage に保存します。'
branding:
  icon: 'eye'
  color: 'gray-dark'
inputs:
  AZURE_OPEN_AI_KEY:
    description: 'Key of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_ENDPOINT:
    description: 'URL of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_VERSION:
    description: 'Version of custom Azure Open AI API'
    required: true
  AZURE_OPEN_AI_MODEL_NAME:
    description: 'Model Name of custom Azure Open AI'
    required: true
  AZURE_OPEN_AI_MODEL_DEPLOY_NAME:
    description: 'Model deploy name of custom Azure Open AI'
    required: true
  AZURE_OPEN_AI_EMBEDDING_MODEL_NAME:
    description: 'Embedding model name of custom Azure Open AI'
    required: true
  AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME:
    description: 'Embedding model deploy name of custom Azure Open AI'
    required: true
  GOOGLE_APPLICATION_CREDENTIALS_JSON:
    description: 'Google Application Credentials JSON'
    required: true
  GOOGLE_INDEX_BUCKET_NAME:
    description: 'Google Storage Bucket Name'
    required: true
  GITHUB_OWNER:
    description: 'GitHub Owner. (Default value: github.repository_owner )'
    required: false
    default: '${GITHUB_REPOSITORY_OWNER}'
  GITHUB_REPO:
    description: 'GitHub Repo. (Default value: github.repository )'
    required: false
    default: '${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}'
  GITHUB_TOKEN:
    description: 'GitHub Token. (Default value: secrets.GITHUB_TOKEN )'
    required: false
  IGNORE_FILE_EXTENSIONS:
    description: 'Ignore file extenstions.'
    required: false
  IGNORE_DIRECTORIES:
    description: 'Igenore directories.'
    required: false
  GITHUB_BRANCH:
    description: 'GitHub Branch.'
    required: false
  GITHUB_COMMIT_SHA:
    description: 'GitHub Commit SHA.'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install gpt-code-generator

    - name: Save precondition indexes from GitHub repositry for generate code
      shell: bash
      run: |
        if -n "${{ inputs.GITHUB_COMMIT_SHA }}" ; then
          save-code-generating-precondition --commit-sha ${{ inputs.GITHUB_COMMIT_SHA }}
        elif -n "${{ inputs.GITHUB_BRANCH }}" ; then
          save-code-generating-precondition --branch ${{ inputs.GITHUB_BRANCH }}
        else
          save-code-generating-precondition
        fi
      env:
        AZURE_OPEN_AI_KEY: ${{ inputs.AZURE_OPEN_AI_KEY }}
        AZURE_OPEN_AI_ENDPOINT: ${{ inputs.AZURE_OPEN_AI_ENDPOINT }}
        AZURE_OPEN_AI_VERSION: ${{ inputs.AZURE_OPEN_AI_VERSION }}
        AZURE_OPEN_AI_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_NAME }}
        AZURE_OPEN_AI_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_MODEL_DEPLOY_NAME }}
        AZURE_OPEN_AI_EMBEDDING_MODEL_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_NAME }}
        AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME: ${{ inputs.AZURE_OPEN_AI_EMBEDDING_MODEL_DEPLOY_NAME }}
        GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'
        GOOGLE_INDEX_BUCKET_NAME: ${{ inputs.GOOGLE_INDEX_BUCKET_NAME }}
        GOOGLE_INDEX_FILE_NAME: ${{ inputs.GOOGLE_INDEX_FILE_NAME }}
        GITHUB_OWNER: ${{ inputs.GITHUB_OWNER }}
        GITHUB_REPO: ${{ inputs.GITHUB_REPO }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        IGNORE_FILE_EXTENSIONS: ${{ inputs.IGNORE_FILE_EXTENSIONS }}
        IGNORE_DIRECTORIES: ${{ inputs.IGNORE_DIRECTORIES }}
