name: Check Lint And Build And Test
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: make install
      - run: make lint
      - run: make build
      # - run: make test
