name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: poetry version $(echo $GITHUB_REF | sed -e 's/refs\/tags\/v//')
      - run: make build
      - run: make publish
      - name: Set up Git user name and tag this commit
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Bump version to $(echo $GITHUB_REF | sed -e 's/refs\/tags\/v//')"
          git push
